#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &
picom &
polybar &
connman-ui-gtk &
dunst &
exec setxkbmap -layout us,ru -option grp:win_space_toggle &
xsetroot -cursor_name left_ptr &
kitty ~/fix.sh &

bspc monitor -d 1 2 3 4 5 6

config border_width         4
bspc config window_gap           6
bspc config normal_border_color "#001C3F"
bspc config focused_border_color "#003464"
bspc config urgent_border_color "#E24A4A"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a PolyMC state=floating
bspc rule -a Connman-gtk state=floating
bspc rule -a steam state=floating
bspc rule -a steamwebhelper state=floating
bspc config pointer_motion_interval 5
